### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by ifvictr**
The way you put the dependencies was incorrect. If there are multiple dependencies, do this: `[PurePerms, RandomPlugin, AnotherPlugin...]`.

### CODE REVIEW

**Comment by DaPigGuy** [comment]
It isn't incorrect.

**Comment by Gamecrafter** [comment]
No, if you have to put brackets around the dependencies if there is more than one. Since he has only one dependency, he should put it like `depend: PurePerms`, not like the way he did it...

**Comment by DaPigGuy** [comment]
Putting it his way works too :stuck_out_tongue:

**Comment by MCPEPIG** [comment]
Keep disagreeing.I dont care if you continue disagreeing or not. You can try it which you won't do because you think its a waste of your time.

**Comment by Gamecrafter** [comment]
?

**Comment by ifvictr** [comment]
Yep I screwed up. I just see brackets as the way to go, dang I forgot about that. :palm_tree: But why have it like that when it's only one dependency?

**Comment by PixelGuy75** [comment]
It is what it is.

**Comment by ifvictr** [comment]
Yeh, I guess you're right, but still try to use brackets. :wink:

**Pull request closed without merging**
